export const figmaToTailwind = new Map([
  ['colors', 'color'],
  ['borderSize', 'border-width'],
  ['padding', 'spacing'],
  ['spacing', 'spacing'],
  ['borderRadius', 'radius'],
  ['fontSize', 'text'],
  ['fontFamily', 'font-family'],
  ['fontWeight', 'font-weight'],
  ['lineHeight', 'leading'],
  ['letterSpace', 'letter-spacing'],
  ['height', 'height'],
  ['maxWidth', 'max-width'],
  ['breakpoints', 'breakpoint'],
  ['zIndex', 'z-index'],
  ['aspectRatio', 'aspect-ratio'],
  ['backgroundColor', 'color'],
  ['textColor', 'text'],
  ['borderColor', 'color'],
  ['borderWidth', 'border-width-width'], // this is stupid, but Tailwind references border-width as border, and we need it to be border-width, or else it will clash with other border properties
  ['transitionTimingFunction', 'ease-in-out'],
  ['containers', 'container'],
  ['gridTemplateColumns', 'grid-cols'],
  ['keyframes', 'keyframes'],
  ['dropShadow', 'drop-shadow'],
]);